# Generated by Django 4.2 on 2023-04-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribers_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество подписчиков')),
                ('created_at', models.DateTimeField(verbose_name='Дата добавления лога')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='channel.channel', verbose_name='Канал')),
                ('post', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='channel.post', verbose_name='Пост')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
